image: alpine/edge
packages:
  - ginkgo
  - go
  - mage
sources:
  - https://git.sr.ht/~kiba/repos
tasks:
  - lint: |
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0
      PATH="$(go env GOPATH)"/bin:$PATH
      golangci-lint --version
      cd repos
      mage -v lint
  - test: |
      cd repos
      git config --global user.email "jane.mc.hacker@notld"
      git config --global user.name "Jane McHacker"
      mage -v test
