stages:
  - test

variables:
  MAGE_VER: "1.9.0"
  LINT_VER: "1.23.7"

.use-golang-image: &use-golang
  image: golang:1.14
  before_script:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin "v$LINT_VER"
    - curl -sSfLO "https://github.com/magefile/mage/releases/download/v$MAGE_VER/mage_${MAGE_VER}_Linux-64bit.tar.gz"
    - tar -xzvf "mage_${MAGE_VER}_Linux-64bit.tar.gz" -C /usr/local/bin
    - rm "mage_${MAGE_VER}_Linux-64bit.tar.gz"
    - GOPATH="$(mktemp -d)"
    - go get -u github.com/onsi/ginkgo/ginkgo
    - mv "$GOPATH/bin/"* /go/bin/
    - rm -rf "$GOPATH"
    - go mod download

lint:
  <<: *use-golang
  stage: test
  services:
  script:
    - mage lint

test:
  <<: *use-golang
  stage: test
  services:
  script:
    - git config --global user.email "jane.mc.hacker@notld"
    - git config --global user.name "Jane McHacker"
    - mage test
