run:
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - typecheck
    - deadcode
    - golint
    - gosec
    - interfacer
    - unconvert
    - goconst
    - gocyclo
    - gofmt
    - maligned
    - misspell
    - lll
    - unparam
    - prealloc
    - scopelint
    - gocritic
    - gochecknoinits
    - gochecknoglobals
    - godox
    - whitespace
    - wsl
  enable-all: false

linters-settings:
  gocyclo:
    min-complexity: 12
  govet:
    check-shadowing: true
  misspell:
    locale: US
  lll:
    line-length: 80
    tab-width: 4
